
class HomeLocators:
    restaurants_btn ="/html/body/div/div/div[4]/div/div/div/div[3]/div[2]"
    save_btn = "/html/body/div/div/div[4]/div/div/div/button"
    Promotions_btn = "/html/body/div/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/a[1] "
    Canabis_btn = "/html/body/div/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/a[2]"
    Drinks_btn = "/html/body/div/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/a[3]"
    New_product_upload_btn ="/html/body/div/div/div[2]/div[2]/div/div/div[1]/div/div/div[2]/a[4]/span"
    Login_btn = "/html/body/div/div/div[2]/header/div/div/a[1]/span[1]"
    pop_up_Login = "/html/body/div[1]/div/div[4]/div"
    logo_btn = "/html/body/div[1]/div/div[2]/header/div/div/a[2]/div/a/img"
    image_logo = "/html/body/div[1]/div/div[2]/header/div/div/a[2]/div"
    image_bar_right_btn = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div/div/button[2]"
    image_1 = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div/div/div/ul/li[2]/a"
    image_2 = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div/div/div/ul/li[3]/a"
    image_bar_left_btn = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div/div/button[1]"
    image_3 = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[1]/div[1]/div/div/div/ul/li[9]/a"
    Shopping_Cart_window = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[1]"
    Max_Business_window = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[2]"
    Max_Business_window_link = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/a"
    Common_questions = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[3]"
    Common_questions_link = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[3]/div/a"
    Contact_window = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[4]"
    Contact_link = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[4]/div/a"
    How_does_shipping_work ="/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[5]"
    How_does_shipping_work_link = "/html/body/div/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div[5]/div/a"