

class Personal_AreaLocators:
    personal_area_btn = "/html/body/div/div/div[2]/header/div/div/a[1]/span[1]"
    My_wallet_window = "/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[1]"
    Products_arena_window = "/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[2]"
    Previous_Orders_window = "/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[3]"
    link_Previous_Orders = "/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[3]/div[3]/span/a/label"
    Orders_for_collection_window = "/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[4]"
    link_Orders_for_collection ="/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[4]/div[3]/span/a/label"
    Delivery_details_window = "/html/body/div[1]/div/div[2]/div[2]/div/div[3]"
    Edit_btn = "/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[4]"
    first_name = "/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[1]/div[1]/span/input"
    last_name ="/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[1]/div[2]/span/input"
    phone ="/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[1]/div[3]/span/input"
    mail ="/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[1]/div[4]/span/input"
    HF_num ="/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[1]/div[5]/span/input"
    street_city ="/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[2]/div/div[1]/div[1]/input"
    street_number ="/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/div[2]/div/div[1]/div[2]/span/input"
    save_btn = "/html/body/div[1]/div/div[2]/div[2]/div/div[3]/form/input"
    error_message = "form_note "
