
class RegistrationLocators:
    connection_btn = "/html/body/div/div/div[2]/header/div/div/a[1]/span[1]"
    registration_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/div[1]/span[2]"
    phone_input = "/html/body/div[1]/div/div[4]/div/div/div/div/form/div[1]/div[1]/span/input"
    HF_EM_input = "/html/body/div[1]/div/div[4]/div/div/div/div/form/div[1]/div[2]/span/input"
    Accept_regulations = "/html/body/div[1]/div/div[4]/div/div/div/div/form/div[1]/div[3]/span/label"
    login_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/form/input"
    error_message = "/html/body/div[1]/div/div[4]/div/div/div/div/form/div[3]"
    code_window = "/html/body/div[1]/div/div[4]/div"
    Twitter_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/div[3]/div[1]/div/img"
    Google_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/div[3]/div[1]/button/img"
    phone_error_message ="/html/body/div[1]/div/div[4]/div/div/div/div/form/div[1]/div[1]/div"
    privacy_policy_error_message = "/html/body/div[1]/div/div[4]/div/div/div/div/form/div[3]"
    code_input = "/html/body/div[1]/div/div[4]/div/div/div/div/form/div[1]/div[1]/span/input"
    validation_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/form/input"
    restaurants_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/div/div[2]/div[2]"
    creat_acount_btn = "/html/body/div[1]/div/div[4]/div/div/div/div/div/div[3]/button"
    user_name = "/html/body/div[1]/div/div[2]/header/div/div/a[1]/span[1]"